name: deploy to gh-pages
on: push
jobs:
  deploy-build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
       with:
        node-version: '16'
     - run: npm install gh-pages --save-dev
     - run: npm run deploy