name: Deploy React App

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: Use Node.js 14
        with:
          node-version: 16
      - run: npm ci
        
      - run: npm run build
        env:
          CI: false
      - run: ls
      - name: Copy build to the build repository
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: build
          dst_path: /.
          dst_owner: jonaslng
          dst_repo_name: schgeno-builds
          dst_branch: main
          
    